"""empty message

Revision ID: 28099be21801
Revises: 
Create Date: 2020-05-28 19:48:20.740978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28099be21801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_per_period')
    op.add_column('game_cost_calendar', sa.Column('price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_cost_calendar', 'price')
    op.create_table('price_per_period',
    sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.PrimaryKeyConstraint('price'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
