"""empty message

Revision ID: 5d49d5401095
Revises: 
Create Date: 2020-05-12 12:23:42.505365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d49d5401095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_utilizador', sa.Integer(), nullable=False),
    sa.Column('uti_nome', sa.String(length=64), nullable=True),
    sa.Column('uti_sobrenome', sa.String(length=64), nullable=True),
    sa.Column('uti_email', sa.String(length=120), nullable=True),
    sa.Column('uti_password', sa.String(length=128), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_utilizador')
    )
    op.create_index(op.f('ix_user_uti_email'), 'user', ['uti_email'], unique=True)
    op.create_index(op.f('ix_user_uti_nome'), 'user', ['uti_nome'], unique=True)
    op.create_index(op.f('ix_user_uti_sobrenome'), 'user', ['uti_sobrenome'], unique=True)
    op.drop_table('estado')
    op.drop_table('utilizadores')
    op.drop_table('plataforma')
    op.drop_table('genero')
    op.drop_table('jogo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogo',
    sa.Column('id_jogo', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_gen', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_plat', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nome_jogo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('preco_jogo', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('classificacao_jogo', mysql.INTEGER(display_width=100), autoincrement=False, nullable=False),
    sa.Column('data_lanc_jogo', sa.DATE(), nullable=False),
    sa.Column('marca_jogo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('desc_jogo', mysql.TEXT(), nullable=False),
    sa.Column('capa_jogo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('preview1_jogo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('preview2_jogo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('preview3_jogo', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_gen'], ['genero.id_gen'], name='jogo_ibfk_1'),
    sa.ForeignKeyConstraint(['id_plat'], ['plataforma.id_plat'], name='jogo_ibfk_2'),
    sa.PrimaryKeyConstraint('id_jogo'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('genero',
    sa.Column('id_gen', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome_gen', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_gen'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('plataforma',
    sa.Column('id_plat', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome_plat', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_plat'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('utilizadores',
    sa.Column('id_utilizador', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uti_nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('uti_sobrenome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('uti_password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('uti_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_utilizador'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('estado',
    sa.Column('novo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('ativo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('banido', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_user_uti_sobrenome'), table_name='user')
    op.drop_index(op.f('ix_user_uti_nome'), table_name='user')
    op.drop_index(op.f('ix_user_uti_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
