"""empty message

Revision ID: fb4db2c12c03
Revises: 9958acbfad9c
Create Date: 2020-06-03 15:45:58.189836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb4db2c12c03'
down_revision = '9958acbfad9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_games_game_review', table_name='games')
    op.drop_column('games', 'game_review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_review', mysql.VARCHAR(length=120), nullable=True))
    op.create_index('ix_games_game_review', 'games', ['game_review'], unique=False)
    # ### end Alembic commands ###
